name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: "Unit Tests Java ${{ matrix.java }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 10, 15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: ./gradlew build

  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
